### PR TITLE
Anish_problem_7.py

### PR DESCRIPTION
**Pull request by Anish528**

### CODE REVIEW

**Review by AnantaSrikar — CHANGES_REQUESTED** [review]
@Anish528 the file name is still unchanged. Please check and change.

**Comment by Anish528** [comment]
Should I close this pull request and upload again?

**Comment by AnantaSrikar** [comment]
I'll fix it for you now. Make sure your other files have the proper format 👍

**Review by AnantaSrikar — APPROVED** [review]
Will merge.

**Comment by Anish528** [comment]
Thank you

**Pull request merged**
