### PR TITLE
Problem 1

### PR DESCRIPTION
**Pull request by TanviKandalla**
Hey, I've solved problem 1 on python...
Thanks!

### CODE REVIEW

**Comment by AnantaSrikar** [comment]
Hey @TanviKandalla ! You've just solved 2 problems in one PR, you will have to solve one more extra if this gets merged. Let me know if you want to fix this.

**Comment by TanviKandalla** [comment]
Oof I did not realise that the commits would get merged into one PR…Yeah, it would be great if you could tell me to fix this… If it’s not possible I can do a few extra problems as well that’s not a huge issue

**Comment by AnantaSrikar** [comment]
Message me on Discord if you want to fix it :+1:

**Review by AnantaSrikar — APPROVED** [review]
Looks good, will merge.

**Pull request merged**
